%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: D:\DI_Data\PartD_Prescriber_PUF_NPI_14\PartD.xlsx Worksheet:
%    Sheet1
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2017/02/06 14:28:40

%% Import the data
[~, ~, raw] = xlsread('D:\DI_Data\PartD_Prescriber_PUF_NPI_14\PartD.xlsx','Sheet1');
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};
cellVectors = raw(:,[2,3,4,5,6,7,8,9,10,13,14,15,16,17]);
raw = raw(:,[1,11,12,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63]);

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Allocate imported array to column variable names
NPI = data(:,1);
NPPES_PROVIDER_LAST_ORG_NAME = cellVectors(:,1);
NPPES_PROVIDER_FIRST_NAME = cellVectors(:,2);
NPPES_PROVIDER_MI = cellVectors(:,3);
NPPES_CREDENTIALS = cellVectors(:,4);
NPPES_PROVIDER_GENDER = cellVectors(:,5);
NPPES_ENTITY_CODE = cellVectors(:,6);
NPPES_PROVIDER_STREET1 = cellVectors(:,7);
NPPES_PROVIDER_STREET2 = cellVectors(:,8);
NPPES_PROVIDER_CITY = cellVectors(:,9);
NPPES_PROVIDER_ZIP5 = data(:,2);
NPPES_PROVIDER_ZIP4 = data(:,3);
NPPES_PROVIDER_STATE = cellVectors(:,10);
NPPES_PROVIDER_COUNTRY = cellVectors(:,11);
SPECIALTY_DESCRIPTION = cellVectors(:,12);
DESCRIPTION_FLAG = cellVectors(:,13);
MEDICARE_PRVDR_ENROLL_STATUS = cellVectors(:,14);
BENE_COUNT = data(:,4);
TOTAL_CLAIM_COUNT = data(:,5);
TOTAL_DRUG_COST = data(:,6);
TOTAL_DAY_SUPPLY = data(:,7);
BENE_COUNT_GE65 = data(:,8);
BENE_COUNT_GE65_SUPPRESS_FLAG = data(:,9);
TOTAL_CLAIM_COUNT_GE65 = data(:,10);
GE65_SUPPRESS_FLAG = data(:,11);
TOTAL_DRUG_COST_GE65 = data(:,12);
TOTAL_DAY_SUPPLY_GE65 = data(:,13);
BRAND_CLAIM_COUNT = data(:,14);
BRAND_SUPPRESS_FLAG = data(:,15);
BRAND_DRUG_COST = data(:,16);
GENERIC_CLAIM_COUNT = data(:,17);
GENERIC_SUPPRESS_FLAG = data(:,18);
GENERIC_DRUG_COST = data(:,19);
OTHER_CLAIM_COUNT = data(:,20);
OTHER_SUPPRESS_FLAG = data(:,21);
OTHER_DRUG_COST = data(:,22);
MAPD_CLAIM_COUNT = data(:,23);
MAPD_SUPPRESS_FLAG = data(:,24);
MAPD_DRUG_COST = data(:,25);
PDP_CLAIM_COUNT = data(:,26);
PDP_SUPPRESS_FLAG = data(:,27);
PDP_DRUG_COST = data(:,28);
LIS_CLAIM_COUNT = data(:,29);
LIS_SUPPRESS_FLAG = data(:,30);
LIS_DRUG_COST = data(:,31);
NONLIS_CLAIM_COUNT = data(:,32);
NONLIS_SUPPRESS_FLAG = data(:,33);
NONLIS_DRUG_COST = data(:,34);
OPIOID_BENE_COUNT = data(:,35);
OPIOID_CLAIM_COUNT = data(:,36);
OPIOID_DRUG_COST = data(:,37);
OPIOID_DAY_SUPPLY = data(:,38);
ANTIBIOTIC_BENE_COUNT = data(:,39);
ANTIBIOTIC_CLAIM_COUNT = data(:,40);
ANTIBIOTIC_DRUG_COST = data(:,41);
HRM_BENE_COUNT_GE65 = data(:,42);
HRM_BENE_GE65_SUPPRESS_FLAG = data(:,43);
HRM_CLAIM_COUNT_GE65 = data(:,44);
HRM_GE65_SUPPRESS_FLAG = data(:,45);
HRM_DRUG_COST_GE65 = data(:,46);
ANTI_PSYCH_BENE_COUNT = data(:,47);
ANTI_PSYCH_CLAIM_COUNT = data(:,48);
ANTI_PSYCH_DRUG_COST = data(:,49);

%% Clear temporary variables
clearvars data raw cellVectors R;