%% Import data from text file.
% Script for importing data from the following text file:
%
%    D:\DI_Data\PartD_Prescriber_PUF_NPI_14\PartD_Prescriber_PUF_NPI_14.txt
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2017/02/06 15:57:25

%% Initialize variables.
filename = 'D:\DI_Data\PartD_Prescriber_PUF_NPI_14\PartD_Prescriber_PUF_NPI_14.txt';
delimiter = '\t';
startRow = 2;

%% Format string for each line of text:
%   column1: double (%f)
%	column2: text (%s)
%   column3: text (%s)
%	column4: text (%s)
%   column5: text (%s)
%	column6: text (%s)
%   column7: text (%s)
%	column8: text (%s)
%   column9: text (%s)
%	column10: text (%s)
%   column11: double (%f)
%	column12: double (%f)
%   column13: text (%s)
%	column14: text (%s)
%   column15: text (%s)
%	column16: text (%s)
%   column17: text (%s)
%	column18: double (%f)
%   column19: double (%f)
%	column20: double (%f)
%   column21: double (%f)
%	column22: text (%s)
%   column23: text (%s)
%	column24: double (%f)
%   column25: text (%s)
%	column26: double (%f)
%   column27: double (%f)
%	column28: double (%f)
%   column29: text (%s)
%	column30: double (%f)
%   column31: double (%f)
%	column32: text (%s)
%   column33: double (%f)
%	column34: double (%f)
%   column35: text (%s)
%	column36: double (%f)
%   column37: double (%f)
%	column38: text (%s)
%   column39: double (%f)
%	column40: double (%f)
%   column41: text (%s)
%	column42: double (%f)
%   column43: double (%f)
%	column44: text (%s)
%   column45: double (%f)
%	column46: double (%f)
%   column47: text (%s)
%	column48: double (%f)
%   column49: double (%f)
%	column50: double (%f)
%   column51: double (%f)
%	column52: double (%f)
%   column53: double (%f)
%	column54: double (%f)
%   column55: double (%f)
%	column56: double (%f)
%   column57: text (%s)
%	column58: double (%f)
%   column59: text (%s)
%	column60: double (%f)
%   column61: double (%f)
%	column62: double (%f)
%   column63: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%s%s%s%s%s%s%s%s%s%f%f%s%s%s%s%s%f%f%f%f%s%s%f%s%f%f%f%s%f%f%s%f%f%s%f%f%s%f%f%s%f%f%s%f%f%s%f%f%f%f%f%f%f%f%f%s%f%s%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines' ,startRow-1, 'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
NPI = dataArray{:, 1};
NPPES_PROVIDER_LAST_ORG_NAME = dataArray{:, 2};
NPPES_PROVIDER_FIRST_NAME = dataArray{:, 3};
NPPES_PROVIDER_MI = dataArray{:, 4};
NPPES_CREDENTIALS = dataArray{:, 5};
NPPES_PROVIDER_GENDER = dataArray{:, 6};
NPPES_ENTITY_CODE = dataArray{:, 7};
NPPES_PROVIDER_STREET1 = dataArray{:, 8};
NPPES_PROVIDER_STREET2 = dataArray{:, 9};
NPPES_PROVIDER_CITY = dataArray{:, 10};
NPPES_PROVIDER_ZIP5 = dataArray{:, 11};
NPPES_PROVIDER_ZIP4 = dataArray{:, 12};
NPPES_PROVIDER_STATE = dataArray{:, 13};
NPPES_PROVIDER_COUNTRY = dataArray{:, 14};
SPECIALTY_DESCRIPTION = dataArray{:, 15};
DESCRIPTION_FLAG = dataArray{:, 16};
MEDICARE_PRVDR_ENROLL_STATUS = dataArray{:, 17};
BENE_COUNT = dataArray{:, 18};
TOTAL_CLAIM_COUNT = dataArray{:, 19};
TOTAL_DRUG_COST = dataArray{:, 20};
TOTAL_DAY_SUPPLY = dataArray{:, 21};
BENE_COUNT_GE65 = dataArray{:, 22};
BENE_COUNT_GE65_SUPPRESS_FLAG = dataArray{:, 23};
TOTAL_CLAIM_COUNT_GE65 = dataArray{:, 24};
GE65_SUPPRESS_FLAG = dataArray{:, 25};
TOTAL_DRUG_COST_GE65 = dataArray{:, 26};
TOTAL_DAY_SUPPLY_GE65 = dataArray{:, 27};
BRAND_CLAIM_COUNT = dataArray{:, 28};
BRAND_SUPPRESS_FLAG = dataArray{:, 29};
BRAND_DRUG_COST = dataArray{:, 30};
GENERIC_CLAIM_COUNT = dataArray{:, 31};
GENERIC_SUPPRESS_FLAG = dataArray{:, 32};
GENERIC_DRUG_COST = dataArray{:, 33};
OTHER_CLAIM_COUNT = dataArray{:, 34};
OTHER_SUPPRESS_FLAG = dataArray{:, 35};
OTHER_DRUG_COST = dataArray{:, 36};
MAPD_CLAIM_COUNT = dataArray{:, 37};
MAPD_SUPPRESS_FLAG = dataArray{:, 38};
MAPD_DRUG_COST = dataArray{:, 39};
PDP_CLAIM_COUNT = dataArray{:, 40};
PDP_SUPPRESS_FLAG = dataArray{:, 41};
PDP_DRUG_COST = dataArray{:, 42};
LIS_CLAIM_COUNT = dataArray{:, 43};
LIS_SUPPRESS_FLAG = dataArray{:, 44};
LIS_DRUG_COST = dataArray{:, 45};
NONLIS_CLAIM_COUNT = dataArray{:, 46};
NONLIS_SUPPRESS_FLAG = dataArray{:, 47};
NONLIS_DRUG_COST = dataArray{:, 48};
OPIOID_BENE_COUNT = dataArray{:, 49};
OPIOID_CLAIM_COUNT = dataArray{:, 50};
OPIOID_DRUG_COST = dataArray{:, 51};
OPIOID_DAY_SUPPLY = dataArray{:, 52};
ANTIBIOTIC_BENE_COUNT = dataArray{:, 53};
ANTIBIOTIC_CLAIM_COUNT = dataArray{:, 54};
ANTIBIOTIC_DRUG_COST = dataArray{:, 55};
HRM_BENE_COUNT_GE65 = dataArray{:, 56};
HRM_BENE_GE65_SUPPRESS_FLAG = dataArray{:, 57};
HRM_CLAIM_COUNT_GE65 = dataArray{:, 58};
HRM_GE65_SUPPRESS_FLAG = dataArray{:, 59};
HRM_DRUG_COST_GE65 = dataArray{:, 60};
ANTI_PSYCH_BENE_COUNT = dataArray{:, 61};
ANTI_PSYCH_CLAIM_COUNT = dataArray{:, 62};
ANTI_PSYCH_DRUG_COST = dataArray{:, 63};


%% Clear temporary variables
clearvars filename delimiter startRow formatSpec fileID dataArray ans;